name: NanoPi R2S FriendlyWrt Build

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev upx-ucl
          sudo -E apt-get -qq install lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo 
          sudo -E apt-get -qq install libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget swig
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          git config --global user.email "chinaluopiao@gmail.com" && git config --global user.name "luopiao"
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash

      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Download Source
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          repo sync -c  --no-clone-bundle

      - name: Upgrade Libcap
        run: |
          cd friendlywrt-rk3328
          git clone https://github.com/openwrt/packages.git
          rm -rf friendlywrt/package/libs/libcap
          cp -r packages/libs/libcap friendlywrt/package/libs/
          cat friendlywrt/package/libs/libcap/Makefile


      - name: Install OpenClash
        run: |
          cd friendlywrt-rk3328/friendlywrt/
          echo "src-git openclash https://github.com/vernesong/OpenClash.git" >> feeds.conf.default

      - name: Update Feeds
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Update Target.mk
        run: |
          cd friendlywrt-rk3328/friendlywrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk

      - name: Write Config
        run: |
          cd friendlywrt-rk3328
          echo "CONFIG_FEED_openclash=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_luci-app-openclash=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_iptables-mod-tproxy=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_iptables=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_dnsmasq-full=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_coreutils=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_coreutils-nohup=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_bash=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_libcurl=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_jsonfilter=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_ca-certificates=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_ipset=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_ip-full=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_iptables-mod-extra=y" >> configs/config_rk3328
          echo "CONFIG_PACKAGE_libcap-bin=y" >> configs/config_rk3328
          cat configs/config_rk3328

      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          ./build.sh nanopi_r2s.mk

      - name: Assemble Artifact
        run: |
          mkdir -p ./artifact/
          find friendlywrt-rk3328/out/ -name "FriendlyWrt_*img*" | xargs -I{} sh -c 'f=$(basename $1); zip -r -j "./artifact/${f}.zip" $1' sh {} \;
          cp friendlywrt-rk3328/friendlywrt/.config ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FriendlyWrt-NanoPi-R2S
          path: |
            artifact